config/routes.rb
Rails.application.routes.draw do
  resources :patients

end

app/models/admission.rb
require 'date_time_format'
require 'description_format'

class Admission < ApplicationRecord
  include DateTimeFormat
  include DescriptionFormat

  has_many :diagnoses
  has_many :symptoms
  has_many :observations
  belongs_to :patient
  belongs_to :facility
  alias_attribute :moment, :created_at

  def diagnoses_description
    formatted_description_for diagnoses
  end

  def symptoms_description
    formatted_description_for(symptoms).downcase
  end

  def observations_description
    formatted_description_for(observations).capitalize
  end
end

app/models/allergy.rb
class Allergy < ApplicationRecord
  validates_presence_of :description
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diagnosis.rb
class Diagnosis < ApplicationRecord
  belongs_to :patient
  belongs_to :admission

  validates_presence_of :description

  scope :chronic_conditions, -> { where(chronic_condition: true) }
  scope :regular_diagnoses, -> { where(chronic_condition: [nil, false]) }
end

app/models/diagnostic_procedure.rb
require 'date_time_format'

class DiagnosticProcedure < ApplicationRecord
  include DateTimeFormat
  validates_presence_of :description
  alias_attribute :moment, :created_at
end

app/models/facility.rb
class Facility < ApplicationRecord
  has_many :admissions
  has_many :patients, through: :admissions

  validates_presence_of :name
end

app/models/medication_order.rb
class MedicationOrder < ApplicationRecord
  enum mass_unit: [:mg]
  enum medication_route: [:PO, :IM, :SC]

  has_one :frequency, foreign_key: 'medication_order_id', class_name: 'OrderFrequency'

  validates_presence_of :name, :mass_unit, :dosage, :frequency

  def unit
    mass_unit
  end

  def route
    medication_route
  end

  def dosage_decimal
    dosage.to_s.sub(/\.?0+$/, '')
  end

  def frequency_value
    frequency.value
  end

  private

  class << self
    def unit
      mass_units
    end

    def route
      medication_routes
    end
  end
end

app/models/observation.rb
class Observation < ApplicationRecord
  belongs_to :admission
  validates_presence_of :description
  alias_attribute :moment, :created_at
end

app/models/order_frequency.rb
class OrderFrequency < ApplicationRecord
  enum unit: [:hr]
  validates_presence_of :value, :unit
end

app/models/patient.rb
require 'description_format'

class Patient < ApplicationRecord
  include DescriptionFormat

  enum gender: [:male, :female, :other]

  has_one :admission
  has_one :facility, through: :admission

  has_many :allergies
  has_many :medications, foreign_key: "patient_id", class_name: "MedicationOrder"
  has_many :diagnostic_procedures
  has_many :diagnoses
  has_many :treatments

  validates_presence_of :first_name, :middle_name, :last_name, :medical_record, :gender
  validates :medical_record, numericality: { only_integer: true,
                                             greater_than_or_equal_to: 10000,
                                             less_than_or_equal_to: 99999 }
  validates :gender, inclusion: { in: ['male', 'female', 'other'] }

  def emergency_transfer_summary
    [
        "This #{age} years old #{gender} was admitted to #{facility.name} emergency facility "\
        "on #{admission.formatted_date} at #{admission.formatted_time} due to #{admission.diagnoses_description}. "\
        "The observed symptoms on admission were #{admission.symptoms_description}. "\
        "#{admission.observations_description}.",

        "Upon asking about known allergies, the patient disclosed #{allergies_description}. "\
        "Upon asking about chronic conditions, the patient disclosed #{chronic_conditions_description}. "\
        "The patient was administered with #{medication_administered}.",

        "The staff performed #{procedures_description}, revealing #{diagnoses_description}. Our team proceeded "\
        "#{treatments_description}."
    ].join("\n\n<br><br>")
  end

  def age
    Time.now.year - dob.year
  end

  def allergies_description
    formatted_description_for allergies
  end

  def chronic_conditions_description
    formatted_description_for chronic_conditions
  end

  def diagnoses_description
    formatted_description_for regular_diagnoses
  end

  def medication_administered
    description = []
    medications.each do |m|
      description << "#{m.name} #{m.dosage_decimal}#{m.unit} #{m.route}"\
                     " #{m.frequency_value}#{m.frequency.unit} to #{m.necessity}"
    end
    description.join(", and ")
  end

  def procedures_description
    description = []
    diagnostic_procedures.each do |p|
      description << "#{p.description} on #{p.formatted_date} at #{p.formatted_time}"
    end
    description.join(", and ")
  end

  def treatments_description
    description = []
    treatments.each { |t| description << "to #{t.description} to #{t.necessity}" }
    description.join(" and ")
  end

  def chronic_conditions
    diagnoses.chronic_conditions
  end

  def regular_diagnoses
    diagnoses.regular_diagnoses
  end
end

app/models/symptom.rb
class Symptom < ApplicationRecord
  belongs_to :admission
  validates_presence_of :description
end

app/models/treatment.rb
class Treatment < ApplicationRecord
  validates_presence_of :description, :necessity
end

app/models/user.rb
class User < ApplicationRecord
  attribute :emergency_staff, :boolean
  scope :emergency_personnel, -> { where(emergency_staff: true) }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: %i[ show edit update destroy ]

  # GET /patients or /patients.json
  def index
    @patients = Patient.all
  end

  # GET /patients/1 or /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients or /patients.json
  def create
    @patient = Patient.new(patient_params)

    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: "Patient was successfully created." }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1 or /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: "Patient was successfully updated." }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1 or /patients/1.json
  def destroy
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: "Patient was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def patient_params
      params.require(:patient).permit(:first_name, :middle_name, :last_name, :medical_record, :dob, :gender)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/patients_helper.rb
module PatientsHelper

  def show_transfer_summary?
    current_user.emergency_staff?
  end

  def current_user
    @current_user ||= User.emergency_personnel.first
    @current_user ||= User.first
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StBernardEmergencyTransferSummary</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
        rel="stylesheet"
        integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
        crossorigin="anonymous">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
          integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
          crossorigin="anonymous"></script>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <%= yield %>
</div>

</body>
</html>

app/views/patients/_emergency_transfer_summary.html.erb
<div class="row">
  <div class="col border header--grey-background">
    <strong>Emergency Transfer Summary (Form 34L-D)</strong>
  </div>
</div>

<div class="row">
  <div class="col border border-top--none">
    <strong>Transferring Facility</strong>
  </div>
</div>

<div class="row border border-top--none">
  <div class="col-sm border border-left--none border-top-bottom--none">
    <p>
      Name:
      <br>
      <%= @patient.facility.name %>
    </p>
  </div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
</div>

<div class="row">
  <div class="col border border-top--none">
    <strong>Patient Information</strong>
  </div>
</div>

<div class="row border border-top--none">
  <div class="col-sm border border-left--none border-top-bottom--none">
    <p>
      First Name
      <br>
      <%= @patient.first_name %>
    </p>
  </div>
  <div class="col-sm border border-left--none border-top-bottom--none">
    <p>
      Middle Name
      <br>
      <%= @patient.middle_name %>
    </p>
  </div>
  <div class="col-sm border border-left--none border-top-bottom--none">
    <p>
      Last Name
      <br>
      <%= @patient.last_name %>
    </p>
  </div>
  <div class="col-sm border border-left--none border-top-bottom--none">
    <p>
      Medical Record (MR)
      <br>
      <%= @patient.medical_record %>
    </p>
  </div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
  <div class="col-sm"></div>
</div>

<div class="row">
  <div class="col-sm border border-top--none">
    <p>
      <strong>Summary</strong>
      <br>
      <br>
      <%= sanitize @patient.emergency_transfer_summary %>
    </p>

  </div>
</div>

app/views/patients/_form.html.erb
<%= form_with(model: patient) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
        <% patient.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :first_name %>
    <%= form.text_field :first_name %>
  </div>

  <div class="field">
    <%= form.label :middle_name %>
    <%= form.text_field :middle_name %>
  </div>

  <div class="field">
    <%= form.label :last_name %>
    <%= form.text_field :last_name %>
  </div>

  <div class="field">
    <%= form.label :medical_record %>
    <%= form.number_field :medical_record %>
  </div>

  <div class="field">
    <%= form.label :dob %>
    <%= form.datetime_select :dob %>
  </div>

  <div class="field">
    <%= form.label :gender %>
    <%= form.number_field :gender %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/patients/edit.html.erb
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Show', @patient %> |
<%= link_to 'Back', patients_path %>

app/views/patients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patients</h1>

<div class="table-responsive">
  <table class="table table-striped table-hover table-bordered">
    <thead>
      <tr>
        <th scope="col">First name</th>
        <th scope="col">Middle name</th>
        <th scope="col">Last name</th>
        <th scope="col">Medical record</th>
        <th scope="col">Dob</th>
        <th scope="col">Gender</th>
        <th colspan="1"></th>
      </tr>
    </thead>

    <tbody>
      <% @patients.each do |patient| %>
        <tr>
          <td><%= patient.first_name %></td>
          <td><%= patient.middle_name %></td>
          <td><%= patient.last_name %></td>
          <td><%= patient.medical_record %></td>
          <td><%= patient.dob %></td>
          <td><%= patient.gender %></td>
          <td><%= link_to 'Show', patient %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/patients/new.html.erb
<h1>New Patient</h1>

<%= render 'form', patient: @patient %>

<%= link_to 'Back', patients_path %>

app/views/patients/show.html.erb
<p id="notice"><%= notice %></p>
<%= render "emergency_transfer_summary" if show_transfer_summary? %>

<br>

<%= link_to 'Back', patients_path %>